CREATE TABLE USUARIOS(
ID_USUARIO INTEGER PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO_PATERNO VARCHAR(30),
APELLIDO_MATERNO VARCHAR(30),
EDAD INT
);

INSERT INTO USUARIOS
	  VALUES(123, 'ELISA', 'AISPURO', 'AISPURO', 21),
			(234, 'NORBERTO', 'ARREDONDO', 'VIZCARRA', 21),
	   		(345, 'MANUEL', 'PALOMARES', 'BRISEÑO', 26);


CREATE TABLE ADMINISTRADORES(
ID_ADMINISTRADOR INTEGER PRIMARY KEY,
NOMBRE VARCHAR(30),
APELLIDO_PATERNO VARCHAR(30),
APELLIDO_MATERNO VARCHAR(30),
EDAD INT
);

INSERT INTO ADMINISTRADORES
	   VALUES(01, 'MARIA', 'SALAZAR', 'LOPEZ', 29),
	     	 (02, 'MITZI', 'ZUNIGA', 'MOLINA', 22),
	   		 (03, 'JUAN', 'HINOJOZA', 'REYES', 21);

CREATE TABLE TICKETS(
FOLIO_TICKET INT PRIMARY KEY,
ASUNTO TEXT,
DESCRIPCION TEXT,
ID_USUARIO INT,
ID_ADMINISTRADOR INT
);

INSERT INTO TICKETS

		VALUES(1, 'INSCRIPCION', 'PAGO DE ALUMNO 2DO AÑO', 123, 01),
			  (2, 'PAGO NO REFLEJADO', 'PAGO REALIZADO Y NO REFLEJADO',234, 02),
			  (3, 'FALLA DE AIRE ACONDICIONADO', 'AULA 4', 345, 03);
			  
			
SELECT * FROM USUARIOS;
SELECT * FROM ADMINISTRADORES;
SELECT * FROM TICKETS;